#!/bin/sh

while true; do
    read -p "Are you sure you want to violently kill all vagrant processes? " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
kill $(ps auwx | grep vagrant | grep -v ssh | awk '{print $2}')
