# -*- mode: ruby -*-
# vi: set ft=ruby :

# Debian 7.7 Wheezy
# http://cloud-images.ubuntu.com/locator/ec2/
# "trusty instance-store amd64 aki"
ami_list = {
    'ap-northeast-1' => 'ami-40e1e641',
    'ap-southeast-1' => 'ami-07597455',
    'ap-southeast-2' => 'ami-39086103',
    'eu-west-1' => 'ami-5a4bfb2d',
    'eu-central-1' => 'ami-d21223cf',
    'sa-east-1' => 'ami-798f3e64',
    'us-east-1' => 'ami-92f569fa',
    'us-west-1' => 'ami-71150534',
    'us-west-2' => 'ami-8b84d0bb'
}

# https://vagrantcloud.com/ubuntu
vmbox = 'ubuntu/trusty64'
ssh_username = 'root'

# Do not override until DEMO-75
# if !ENV['DEMO_AWS_REGION']
#     ENV['DEMO_AWS_REGION'] = 'us-east-1'
# end
ENV['DEMO_AWS_REGION'] = 'us-east-1'

if !ENV['DEMO_AWS_AZ']
    ENV['DEMO_AWS_AZ'] = 'us-east-1a'
end

if !ENV['DEMO_DEV_IP']
    ENV['DEMO_DEV_IP'] = '192.168.133.7'
end

def check_aws_envars()
    required_envars = ['DEMO_AWS_ACCESS_KEY', 'DEMO_AWS_SECRET_KEY',
                       'DEMO_KEYPAIR_NAME', 'DEMO_KEYPAIR_LOCATION',
                       'DEMO_USER', 'DEMO_EMAIL']

    for envar in required_envars
        if !ENV[envar]
            print "\n$#{envar} must be set!\n"
            print "If performing a specific you must specify a "
            print "machine name. Example:\n"
            print "\tvagrant ssh dev\n"
            print "\tvagrant destroy dev\n\n"
            exit
        end
    end
end

def provision(config, production, stale)
    if production
        # export PRODUCTION=1
        config.vm.provision :shell, path: 'src/production.sh', privileged: false
    end

    config.vm.provision :shell, path: 'src/bootstrap.sh', privileged: false

    if stale
        config.vm.provision :file, source: '../keys/demo-portal.key',
                                   destination: '~/.ssh/demo-portal.key'
        config.vm.provision :file, source: '../keys/config',
                                   destination: '~/.ssh/config'

        config.vm.provision :shell, path: 'src/stale_install.sh', privileged: false

        config.vm.provision :file, source: '../../set_credentials.sh',
                                   destination: '/portal/demo-portal/'
        config.vm.provision :file, source: '../../flask2.0/DemoPortalFlask/application.cfg',
                                   destination: '/portal/demo-portal/flask2.0/DemoPortalFlask/'
    end

    config.vm.provision :shell, path: 'src/python.sh', privileged: false
    config.vm.provision :shell, path: 'src/install.sh', privileged: false
    config.vm.provision :shell, path: 'src/vagrant.sh', privileged: false

    if !production
        # start a Dockerized DSE instance

        # use Vagrant to install Docker
        config.vm.provision 'docker', images: ['scratch']

        # setup Docker authentication
        config.vm.provision :shell, path: 'src/docker.sh', privileged: false

        # run Docker container
        config.vm.provision 'docker' do |d|
            d.run 'datastaxdemos/datastax-enterprise', args: '--net host'
        end
    end

    config.vm.provision :shell, path: 'src/run.sh', privileged: false
end


VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # disable default synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true
    
    config.vm.define 'dev', primary: true do |dev|
        # set vm image
        dev.vm.box = vmbox

        # set local ip address
        dev.vm.network 'private_network', ip: ENV['DEMO_DEV_IP']
        dev.vm.post_up_message = "Start the portal using:\n"\
            "\t vagrant ssh dev \n"\
            "\t python /portal/demo-portal/flask2.0/run \n"\
            "then visit the portal at:\n"\
            "\t http://#{ENV['DEMO_DEV_IP']}:5000"

        # set virtualbox size information
        dev.vm.provider 'virtualbox' do |vb|
            vb.memory = 1024
            vb.cpus = 2
            vb.name = 'DataStax Demo Portal (dev)'
        end

        # use synced folders for dev vm setup
        dev.vm.synced_folder '../..',
                             '/portal/demo-portal',
                             create: true
        dev.vm.synced_folder '../cache',
                             '/cache',
                             create: true

        provision(dev, false, false)
    end

    config.vm.define 'dev-stale', primary: true do |dev_stale|
        # set vm image
        dev_stale.vm.box = vmbox

        # set local ip address
        dev_stale.vm.network 'private_network', ip: ENV['DEMO_DEV_IP']
        dev_stale.vm.post_up_message = "Start the portal using:\n"\
            "\t vagrant ssh dev_stale \n"\
            "\t python /portal/demo-portal/flask2.0/run \n"\
            "then visit the portal at:\n"\
            "\t http://#{ENV['DEMO_DEV_IP']}:5000"

        # set virtualbox size information
        dev_stale.vm.provider 'virtualbox' do |vb|
            vb.memory = 1024
            vb.cpus = 2
            vb.name = 'DataStax Demo Portal (dev_stale)'
        end

        provision(dev_stale, false, true)
    end

    # configure aws machines
    config.vm.provider 'aws' do |aws, override|
        # setup aws overrides
        override.vm.box = 'aws-dummy'
        override.ssh.username = ssh_username

        # setup PRODUCTION envar
        override.vm.provision :shell,
            inline: "echo 'export PRODUCTION=1' >> ~/.profile"

        # setup basic aws configurations
        aws.access_key_id = ENV['DEMO_AWS_ACCESS_KEY']
        aws.secret_access_key = ENV['DEMO_AWS_SECRET_KEY']
        aws.region = ENV['DEMO_AWS_REGION']
        aws.availability_zone = ENV['DEMO_AWS_AZ']
        aws.ami = ami_list[aws.region]
        aws.instance_type = 'm3.medium'

        # setup keypair configuration
        aws.keypair_name = ENV['DEMO_KEYPAIR_NAME']
        override.ssh.private_key_path = ENV['DEMO_KEYPAIR_LOCATION']

        # setup security groups
        aws.security_groups = ['demo-portal-launcher']
    end

    config.vm.define 'production-A', autostart: false do |production_A|
        production_A.vm.provider 'aws' do |aws|
            check_aws_envars()

            # setup AWS Tags
            aws.tags = {
                'Name' => 'Demos Portal A (Do NOT Terminate)',
                'Provisioner' => 'demo-portal-launcher',
                'Owner' => ENV['DEMO_USER'],
                'Email' => ENV['DEMO_EMAIL']
            }
        end
    end

    config.vm.define 'production-B', autostart: false do |production_B|
        production_B.vm.provider 'aws' do |aws|
            check_aws_envars()

            # setup AWS Tags
            aws.tags = {
                'Name' => 'Demos Portal B (Do NOT Terminate)',
                'Provisioner' => 'demo-portal-launcher',
                'Owner' => ENV['DEMO_USER'],
                'Email' => ENV['DEMO_EMAIL']
            }
        end
    end

    config.vm.define 'staging', autostart: false do |staging|
        staging.vm.provider 'aws' do |aws|
            check_aws_envars()

            # setup AWS Tags
            aws.tags = {
                'Name' => 'Demos Portal Staging (Do NOT Terminate)',
                'Provisioner' => 'demo-portal-launcher',
                'Owner' => ENV['DEMO_USER'],
                'Email' => ENV['DEMO_EMAIL']
            }
        end
    end

    config.vm.define 'build', autostart: false do |build|
        build.vm.provider 'aws' do |aws|
            check_aws_envars()

            # setup AWS Tags
            aws.tags = {
                'Name' => 'Demos Portal Build Test',
                'Provisioner' => 'demo-portal-launcher',
                'Owner' => ENV['DEMO_USER'],
                'Email' => ENV['DEMO_EMAIL']
            }
        end
    end

    config.ssh.username = 'vagrant'
end
